### ISSUE TITLE
Should be able to edit disabled slaves with (active) mongods

### ISSUE THREAD

**Issue by janisstreib** [KIT-MAMID/mamid#18]
...but should not be able to make portrange smaller

**Comment by bwoebi** [comment]
You mean slaves in maintenance? Slaves in disabled mode should not have active mongods at all.

**Comment by antonxy** [comment]
Disabled slaves might still have mongods running that cant be cleared because the slave is unreachable

**Comment by antonxy** [comment]
Suggestion: also allow editing of slaves in maintenance with the same constraints.
Would be useful if you want to change the hostname/ip/port of a slave without reallocating all mongods.

**Comment by problame** [comment]
Reopen

**Problem description**

* Replica Set is deployed with Mongods on several Slaves, including Slave A.
* => Slave A is hosting Mongods.
* Slave A becomes unreachable.
* Since Master has several Mongods with DesiredState = Running on Slave A, it will
  * attempt to migrate these Mongods away by finding alternative Slaves
  * forbid deletion of the Slave as long as at least one Slave has not been migrated away
* The above cannot be mitigated by reducing member counts in the Replica Set
  * because an unreachable Slave should not count toward `replica_set_effective_member_count`
    * this is the case for slaves that have never been observed because observedstate=NULL and hence the corresponding WHERE clause evaluates negative
    * this is untrue for slaves that have been observed at least once but whose parent slave is unreachable => we need an ObservationError field for the Slave (several TODOs already in code for this)
